language: python
cache: pip
python: "3.6"
install:
  # postgresql should be installed by default
  - sudo apt-get install libpq-dev libicu-dev libgmp-dev libmpfr-dev libmpc-dev
  - sudo -u postgres createuser -s `whoami` || true
matrix:
  include:
    - env: NAME=tests
      install:
        - pip install pipenv
        - pipenv --python python3
        - pipenv sync --dev

      script:
        - pipenv run pytest -v --cov -n 2

      after_success:
        - pipenv run codecov

    - env: NAME=tests-django20
      install:
        - pip install pipenv
        - pipenv sync --dev
        - pip install "Django>=2.0,<2.1"

      script:
        - pipenv run pytest -v --cov -n 2

    - env: NAME=flake8
      install:
        - pip install flake8

      script:
        - flake8 --config=.flake8.travis
