language: python
python:
  - "2.7"
install:
  # postgresql should be installed by default
  - sudo apt-get install libpq-dev libicu-dev libgmp-dev libmpfr-dev libmpc-dev
  - sudo -u postgres createuser -s `whoami` || true
  - createdb zeus_test
  - pip install pipenv
  - pipenv --python python2
  - pipenv sync --dev

script:
  - pipenv run pytest -v --cov

after_success:
  - pipenv run codecov
