language: python
python:
  - "2.7"
install:
  # postgresql should be installed by default
  - sudo apt-get install libpq-dev
  - sudo -u postgres createuser -s `whoami` || true
  - createdb zeus_test
  - ./setup-python

script:
  - . env/bin/activate && py.test -v --cov
  
# TODO change to after_success after tests are passing
after_script:
  - . env/bin/activate && codecov
