- hosts: all
  become: yes
  vars:
    zeus_db_password: "{{ lookup('password', 'secrets/zeus_db_password.' + inventory_hostname + '.txt') }}"
  tasks:

    - name: zeus user
      user:
        name: zeus
        shell: /bin/bash
        home: /srv/zeus/

    - name: www-data user
      user:
        name: www-data
        groups: zeus
        append: yes

    - apt: pkg={{ item }} state=latest
      with_items:
        - postgresql-9.5
        - libpq-dev
        - python-psycopg2
        - libicu-dev
        - libgmp-dev
        - g++

    - name: zeus database
      postgresql_db:
        name: zeus
      become_user: postgres

    - name: zeus postgres user
      postgresql_user:
        name: zeus
        db: zeus
        password: "{{ zeus_db_password }}"
      become_user: postgres

    - name: git repo
      git:
        repo: https://github.com/pwmarcz/zeus.git
        dest: /srv/zeus/install
      become_user: zeus

    - name: settings/local.py
      template:
        src: templates/zeus_settings_local.py
        dest: /srv/zeus/install/settings/local.py
        owner: zeus

    - name: uwsgi.ini
      template:
        src: templates/zeus_uwsgi.ini
        dest: /srv/zeus/uwsgi.ini
        owner: zeus

    - name: /var/run/zeus
      file:
        path: /var/run/zeus
        state: directory
        owner: zeus
        group: zeus
        mode: 0770

    - name: systemd service configuration
      template:
        src: templates/zeus-uwsgi.service
        dest: /etc/systemd/system/zeus-uwsgi.service

    - name: nginx template
      template:
        src: templates/zeus-nginx.conf
        dest: /etc/nginx/sites-available/zeus
      notify: reload nginx

    - name: symlink nginx template
      file:
        src: /etc/nginx/sites-available/zeus
        dest: /etc/nginx/sites-enabled/zeus
        state: link
      notify: reload nginx

  handlers:
    - name: reload nginx
      service: name=nginx state=reloaded
